package credentials

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

func TestVaultLegacyCompatibilityAndKeySafety(t *testing.T) {
	path := filepath.Join(t.TempDir(), "key")
	key := []byte("MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA=\n")
	if err := os.WriteFile(path, key, 0600); err != nil {
		t.Fatal(err)
	}
	vault, err := Open(path, false)
	if err != nil {
		t.Fatal(err)
	}
	// Generated by Python cryptography.Fernet with a synthetic key and plaintext.
	fixture := []byte("gAAAAABfXhAAMopY7fk0z6Znx1qJiJwQbQI7A4z8dao8Ixl7F5ddDV5avA8SDqKcl_HC0t8EdsF8GcBY_qoPGjGOrTtUtGjZjmPmmAZ5uQnhvRXqRi9mP4c=")
	plain, err := vault.Decrypt(fixture)
	if err != nil || string(plain) != "synthetic-test-credential" {
		t.Fatalf("legacy fixture decryption failed: %v", err)
	}
	if vault.Fingerprint() != fmt.Sprintf("sha256:%x", sha256.Sum256(key)) {
		t.Fatal("fingerprint differs from legacy raw-byte fingerprint")
	}
	for _, secret := range [][]byte{nil, []byte("new-credential")} {
		encrypted, err := vault.Encrypt(secret)
		if err != nil {
			t.Fatal(err)
		}
		decoded, err := vault.Decrypt(encrypted)
		if err != nil || !bytes.Equal(decoded, secret) {
			t.Fatalf("round trip failed: %v", err)
		}
	}
	fixture[30] ^= 1
	if _, err := vault.Decrypt(fixture); err == nil {
		t.Fatal("tampered ciphertext accepted")
	}
	other, err := Open(filepath.Join(t.TempDir(), "key"), true)
	if err != nil {
		t.Fatal(err)
	}
	encrypted, _ := vault.Encrypt([]byte("test"))
	if _, err := other.Decrypt(encrypted); err == nil {
		t.Fatal("wrong encryption key accepted")
	}
	if _, err := Open(path, true); err != nil {
		t.Fatal(err)
	}
	actual, _ := os.ReadFile(path)
	if !bytes.Equal(actual, key) {
		t.Fatal("existing encryption key overwritten")
	}
	if err := os.Chmod(path, 0644); err != nil {
		t.Fatal(err)
	}
	if _, err := Open(path, false); err == nil {
		t.Fatal("world-readable key accepted")
	}
	if _, err := Open(filepath.Join(t.TempDir(), "missing"), false); err == nil {
		t.Fatal("missing key silently created")
	}
}
